name: Lua lint

on: 
  workflow_call:
    inputs:
      debug_enabled:
        required: false
        type: boolean
        default: false
      paths:
        required: false
        type: string
        default: script
      config_file:
        required: false
        type: string
        default: .luacheckrc
      custom_lua_globals:
        required: false
        type: string
      vendor_path:
        required: false
        type: string
        default: .luarocks
      lua_version:
        required: false
        type: string
        default: 5.1
      luarocks_version:
        required: false
        type: string
        default: 3.9.1
      pr_enabled:
        required: false
        type: boolean
        default: false
      automerge_enabled:
        required: false
        type: boolean
        default: false
      git_author_name:
        required: false
        type: string
        default: github-actions[bot]
      git_author_email:
        required: false
        type: string
        default: 41898282+github-actions[bot]@users.noreply.github.com
      git_committer_name:
        required: false
        type: string
        default: github-actions[bot]
      git_committer_email:
        required: false
        type: string
        default: 41898282+github-actions[bot]@users.noreply.github.com
    secrets:
      token:
        required: true

env:
  GH_TOKEN: ${{ secrets.token }}
  PROBLEM_MATCHER: luacheck-plain.json
  WORKFLOW_REF: v2
  WORKFLOW_REPO: Warhammer-Mods/workflows

jobs:
  setup-and-lint:
    runs-on: ubuntu-latest
    outputs:
      clean: ${{ steps.changes.outputs.clean }}
      files: ${{ steps.changes.outputs.files }}

    steps:
    - uses: actions/checkout@v3

    - uses: leafo/gh-actions-lua@v9.1.0
      with:
        luaVersion: ${{ inputs.lua_version }}
        
    - uses: leafo/gh-actions-luarocks@v4.3.0
      with:
        luarocksVersion: ${{ inputs.luarocks_version }}
        
    - name: Install luacheck
      run: luarocks install luacheck

    - name: Check if rockspec file is present
      id: rockspec
      run: |
        rockspec=$(
          find . -maxdepth 1 -type f -iname "*.rockspec" \
          | head -n 1 \
          | cut -d/ -f2-
        )

        if [[ -s "${rockspec}" ]]; then
          echo "::set-output name=file_path::${rockspec}"
          echo "::set-output name=is_present::true"
        else
          echo "::set-output name=is_present::false"
        fi

    - uses: actions/cache@v3
      id: cache
      if: steps.rockspec.outputs.is_present == 'true'
      with:
        path: ${{ inputs.vendor_path }}
        key: "${{ runner.os }}-luarocks_vendor_${{ hashFiles('**/*.rockspec') }}"

    - name: Install
      run: |
        luarocks install --tree ${{ inputs.vendor_path }} lua-globals

        if [[ "${{ steps.rockspec.outputs.is_present }}" == "true" ]]; then
          luarocks install --tree ${{ inputs.vendor_path }} --only-deps ${{ steps.rockspec.outputs.file_path }}
        fi

        lr_path=$(luarocks path --tree ${{ inputs.vendor_path }} --lr-path )
        echo "LUA_PATH=${lr_path/;/:}:${LUA_PATH}" >> $GITHUB_ENV

        lr_cpath=$(luarocks path --tree ${{ inputs.vendor_path }} --lr-cpath)
        echo "LUA_CPATH=${lr_cpath/;/:}:${LUA_CPATH}" >> $GITHUB_ENV

        lr_bin=$(luarocks path --tree ${{ inputs.vendor_path }} --lr-bin)
        echo "${lr_bin/;/:}" >> $GITHUB_PATH

    - name: Update lua globals
      env:
        PATHS: ${{ inputs.paths }}
        CONFIG_FILE: ${{ inputs.config_file }}
        LUA_VERSION: ${{ inputs.lua_version }}
        CUSTOM_LUA_GLOBALS: ${{ inputs.custom_lua_globals }}
        DEBUG_ENABLED: ${{ secrets.ACTIONS_STEP_DEBUG == 'true' || inputs.debug_enabled }}
      run: |
        script="update_lua_globals.sh"
        curl -sL --retry 5 \
          "${GITHUB_SERVER_URL}/${{ env.WORKFLOW_REPO }}/raw/${{ env.WORKFLOW_REF }}/bin/${script}" |
        bash

    - name: Get file changes
      id: changes
      run: |
        changes=$(git ls-files \
          --modified \
          --others \
          --exclude-standard \
          ${{ inputs.config_file }}
        )
        echo "::debug::${changes}"

        if [ -z "${changes}" ]; then
          echo "::set-output name=clean::true"
        else
          files=()
          echo "::group::Files changed"
          while IFS= read -r line; do
            files+=("${line}")
            echo "::notice file=${file}::File changed: ${line}"
            echo "::debug::$(git diff ${file})"
          done <<< ${changes}
          echo "::endgroup::"
          echo "::set-output name=files::${files[@]}"
          echo "::set-output name=clean::false"
        fi

    - name: Get workflow info
      id: workflow-info
      env:
        DEBUG_ENABLED: ${{ secrets.ACTIONS_STEP_DEBUG == 'true' || inputs.debug_enabled }}
      run: |
        [ "${DEBUG_ENABLED}" = 'true' ] && set -x

        gh_workflows_json=$(
          gh api -H "Accept: application/vnd.github+json" \
          /repos/${WORKFLOW_REPO}/commits/${WORKFLOW_REF}
        )

        echo "::set-output name=json::${gh_workflows_json}"

    - name: Cache problem matcher
      id: cache-matcher
      uses: actions/cache@v3
      with:
        key: matcher-${{ env.PROBLEM_MATCHER }}-SHA${{ fromJSON(steps.workflow-info.outputs.json).sha }}
        path: matchers/${{ env.PROBLEM_MATCHER }}

    - name: Install problem matcher
      if: steps.cache-matcher.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p matchers
        curl -sL --fail --retry 5 \
          -o matchers/${{ env.PROBLEM_MATCHER }} \
          "${GITHUB_SERVER_URL}/${{ env.WORKFLOW_REPO }}/raw/${{ env.WORKFLOW_REF }}/matchers/${{ env.PROBLEM_MATCHER }}"

    - name: Luacheck Lint
      id: luacheck
      shell: bash --noprofile --norc {0}
      run: |
        echo "::add-matcher::${{ env.PROBLEM_MATCHER }}"

        luacheck ${{ inputs.paths }} \
          --formatter plain \
          --codes --ranges
        exitcode=$?
        
        echo "::remove-matcher owner=luacheck-plain_error::"
        echo "::remove-matcher owner=luacheck-plain_warning::"

        rm -fv ${{ env.PROBLEM_MATCHER }}

        if [ "$exitcode" -gt 1 ]; then
          exit $exitcode
        else
          exit 0
        fi

    - name: Upload updated files
      if: steps.changes.outputs.clean == 'false' && inputs.pr_enabled == true
      uses: actions/upload-artifact@v3
      with:
        name: luacheckrc
        path: ${{ steps.changes.outputs.files }}

  create-pr:
    runs-on: ubuntu-latest
    needs: setup-and-lint
    if: needs.setup-and-lint.outputs.clean == 'false' && inputs.pr_enabled == true

    steps:

    - uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Download updated files
      uses: actions/download-artifact@v3
      with:
        name: luacheckrc

    - name: Commit files
      id: commit
      env:
        GIT_AUTHOR_NAME: ${{ inputs.git_author_name }}
        GIT_AUTHOR_EMAIL: ${{ inputs.git_author_email }}
        GIT_COMMITTER_NAME: ${{ inputs.git_committer_name }}
        GIT_COMMITTER_EMAIL: ${{ inputs.git_committer_email }}
      run: |
        git add ${{ needs.setup-and-lint.outputs.files }}
        git commit -m "Update config and autocomplete"

    - name: Create a PR
      id: pr
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.token }}
        committer: "${{ format(
          '{0} <{1}>',
          inputs.git_committer_name,
          inputs.git_committer_email ) }}"
        author: "${{ format(
          '{0} <{1}>',
          inputs.git_author_name,
          inputs.git_author_email ) }}"
        branch: bot/lua-globals-patch
        delete-branch: true
        signoff: false
        title: "[Luacheck] Update config"
        body: |
          **Update**:
            - Luacheck globals list
        labels: |
          automation
          lua
          dep

    - name: Show info
      run: |
        echo "::notice::${{ format(
          'Pull request #{0} is {1}: {2}',
          steps.pr.outputs.pull-request-number,
          steps.pr.outputs.pull-request-operation,
          steps.pr.outputs.pull-request-url
        ) }}"

    - name: Enable Pull Request Automerge
      if: steps.pr.outputs.pull-request-operation == 'created' && inputs.automerge_enabled == true
      uses: peter-evans/enable-pull-request-automerge@v2
      with:
        token: ${{ secrets.token }}
        pull-request-number: ${{ steps.pr.outputs.pull-request-number }}
        merge-method: squash
